const { configMailMaze } = require('./dist/index');

const mailMaze = configMailMaze({
    emails: [
        { name: 'John Doe', email: 'john.doe@test.com' },
        { name: 'Jane Doe', email: 'jane.doe@test.com' },
        { name: 'Jssie Doe', email: 'jessie.doe@test.com' },
        { name: 'Jake Doe', email: 'jake.doe@test.com' },
        { name: 'Janice Doe', email: 'janice.doe@test.com' },
        { name: 'Jack Doe', email: 'jack.doe@test.com' },
        { name: 'Johan Doe', email: 'johan.doe@test.com' },
        { name: 'Johanna Doe', email: 'johanna.doe@test.com' },
        { name: 'Jim Doe', email: 'jim.doe@test.com' },
        { name: 'Jill Doe', email: 'jill.doe@test.com' },
        { name: 'Samuel Doe', email: 'samuel.doe@test.com' },
        { name: 'John Doe', email: 'john.doe@test.com' },
        { name: 'John Doe', email: 'john.doe@test.com' },
        { name: 'John Doe', email: 'john.doe@test.com' },
        { name: 'John Doe', email: 'john.doe@test.com' },
        { name: 'John Doe', email: 'john.doe@test.com' },
        { name: 'John Doe', email: 'john.doe@test.com' },
        { name: 'John Doe', email: 'john.doe@test.com' },
        { name: 'John Doe', email: 'john.doe@test.com' },
        { name: 'John Doe', email: 'john.doe@test.com' },
        { name: 'John Doe', email: 'john.doe@test.com' },
        { name: 'John Doe', email: 'john.doe@test.com' },
        { name: 'John Doe', email: 'john.doe@test.com' },
        { name: 'John Doe', email: 'john.doe@test.com' },
        { name: 'John Doe', email: 'john.doe@test.com' },
        { name: 'John Doe', email: 'john.doe@test.com' },
        { name: 'John Doe', email: 'john.doe@test.com' },
        { name: 'John Doe', email: 'john.doe@test.com' },
        { name: 'John Doe', email: 'john.doe@test.com' },
    ],
    limit: 10,
    provider: 'sending-blue',
    providerConfig: {
        apiKey: 'otrtuio@665rrGFG€ueiiu4iu4h3',
        sender: {
            name: 'test company',
            email: 'test.company@email.com',
        },
    },
});
console.log(mailMaze);
